easy_admin:
    entities:
        Category:
            class: App\Entity\Services
            form:
                fields:
                    - { property: 'code_service' }
                    - { property: 'nom_service'}
